### ISSUE TITLE
Create a sandbox manager with a REST api that can create a new container to run user code in and return the output of the run code in a marshalled form

### ISSUE THREAD

**Issue by Joeoc2001** [AI-Wars-Soc/submission-runner#1]
This issue concerns the base workings of this system

**Comment by jainris** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Create a sandbox manager with a REST api that can create a new container to run user code in and return the output of the run code in a marshalled form](https://trello.com/c/RcMf7Ei5/14-create-a-sandbox-manager-with-a-rest-api-that-can-create-a-new-container-to-run-user-code-in-and-return-the-output-of-the-run-co)

**Comment by Joeoc2001** [comment]
Completed
